config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get 'levels/:stage_number' => 'levels#show', as: :level

  get 'users/new' => 'users#new'
  post 'users' => 'users#create'
  get 'users/:id' => 'users#show', as: :user

  get '/about' => 'pages#about', as: :about

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  post 'sessions' => 'sessions#create'

  post 'query' => 'gameplay#execute', as: :query
  post 'reset' => 'gameplay#reset_current'

end

app/views/layouts/_header.html.erb
<header>
	<a href="/about"><%= image_tag "missql-logo-8.png", :alt=>"MISSQL COMMAND", :class=>"header-logo" %></a>
	<span class="level-ctrls">
	<% if @level %>
		<% if @level.prev_level %>
			<a href="/levels/<%= @level.prev_level.stage_number %>" class="level-arrow left">↼ Prev</a>
		<% end %>
			<h4><%= "Level #{@level.stage_number}" %></h4>
		<% if @level.next_level %>
			<a href="/levels/<%= @level.next_level.stage_number %>" class="level-arrow right">Next ⇀</a>
		<% end %>			
	<% end %>
	</span>	

	<% if current_user -%>
	<nav>
		<span>Levels ▾</span>
		<ul class="nav-links">
			<% @levels.each do |level| %>
			<li <%= "class = completed" if current_user.has_completed?(level) %>><%= link_to "##{level.stage_number.to_s} #{strip_tags level.title}", "/levels/#{level.stage_number}" %> </li>
			<% end %>
		</ul>
	</nav>
	<% end %>

		<span class="session"><% if current_user && !current_user.guest? -%>
		<%= "#{current_user.display_name} | " -%>
		<%= link_to("Logout", logout_path) -%>
	<% else -%>
		<%= link_to("Sign Up", users_new_path) -%> or
		<%= link_to("Login", login_path) -%>
	<% end -%></span>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MissqlCommand</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body class="<%= controller_name %>">

<%= render "layouts/header" %>
<main role="main" id="content">
<%= yield %>
</main>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50120015-1', 'missqlcommand.com');
  ga('send', 'pageview');

</script>
  <script type="text/javascript">
  WebFontConfig = {
    google: { families: [ 'Glegoo::latin', 'Quantico:400,400italic:latin' ] }
  };
  (function() {
    var wf = document.createElement('script');
    wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
      '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
    wf.type = 'text/javascript';
    wf.async = 'true';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(wf, s);
  })(); </script>
</body>
</html>